# https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    versioning-strategy: lockfile-only
    schedule:
      interval: "weekly"
    labels:
      - "pip"
      - "dependencies"
